### PR TITLE
Upgrade to Slick 3.0.3

### PR DESCRIPTION
**Pull request by jkutner**

### CODE REVIEW

**Comment by renexdev** [comment]
CAPO jkutner!. Was very confusing to find  the proper Procfile (for Heroku) and slick config for Play 2.4 and Slick 3.X.X even from the documentation (at least for a non specialist like me). I followed your upgrade steps in my simple project and works like a charm!  Thanks a lot! ReneX

**Comment by jkutner** [comment]
@renexdev yea, docs on this are a little thin. sorry.

@cneijenhuis can you merge this. I think it's a great working sample now :)

**Comment by cneijenhuis** [comment]
Sorry @jkutner that I didn't merge this yet - forgot about it, really.

@renexdev I initially created this repo to showcase the bug that was in previous versions of Slick. It's fixed thanks to the help of @jkutner now. Didn't expect anyone to turn up here, sorry :)

What is still missing from the Play documentation for you @renexdev ?

**Comment by renexdev** [comment]
Thanks for your help guys. The only concern I had was about the proper config of postgres with slick in heroku (the application.conf and procfile files) koz there is a lot of diverging approaches on internet (like setting up the db connection manually and so on). So it's ok now!. The only thing I've not finished to understand yet is on how to add  in my config files the Hikari CP Module with Postgres on a Heroku app. Cheers

**Comment by jkutner** [comment]
@renexdev i'd suggest opening a ticket at http://help.heroku.com (which will be ultimately routed to me). Or you might ask on the [Play mailing list](https://groups.google.com/forum/#!forum/play-framework).

**Comment by renexdev** [comment]
Perfect @jkutner thks again

**Pull request merged**
